### ISSUE TITLE
the README implies it will just work

### ISSUE THREAD

**Issue by doug-gilbert** [matiassimon/cmake-modules-example#2]
Of course it doesn't and what does the README say? Tried this on Ubuntu 23.10 (bleeding edge) and needed to go to Debian unstable to find cmake 3.28 (U 23.10 ships with 3.27). Really didn't want to attempt building cmake from scratch and cmake.org doesn't supply deb or rpm packages to help Linux users.
    `$ cmake -GNinja . ;  cmake --build . -v`
failed like this:
   `[1/8] "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND" -format=p1689 -- /usr/bin/clang++  ...`
After some poking around I found there is a clang-tools-17 package that contains the clang-scan-deps-17 executable which Ubuntu does **not** install unless explicitly asked. With that installed (and some other fights) it worked, all to compile about 10 lines of C++ !
So some suggestions: please explain in the README what platform it did work on (e.g. OS, compiler, etc). Second when I cloned this repo 27 MBs were downloaded. I think src/hello.pcm should be removed as I'm guessing its an artefact of a VS build. Similarly the .vscode directory can be removed.

**Comment by matiassimon** [comment]
Hi! Thank you for the suggestions! I've improved the README and removed the generated hello.pcm module interface (though the size of the repo will remain the same). I've decided to keep the .vscode folder, as I believe those configurations make the example easier to reproduce.
